### PR TITLE
fix(restafary) onFS: Windows system access file error

### PR DESCRIPTION
**Pull request by wll8**
image

See: [restafary.js#L154](https://github.com/coderaiser/node-restafary/blob/a61dcd095028de1126db63c91ad9165deeb4395d/server/restafary.js#L154)

image

### CODE REVIEW

**Comment by coderaiser** [comment]
Could you please add test for this?

**Comment by wll8** [comment]
do you accept,

This test will only run on windows system?

**Comment by coderaiser** [comment]
> This test will only run on windows system?

Test should run on any system, you can mock the `platform` 

https://github.com/coderaiser/win32/blob/v7.1.0/test/win32.js#L245-L248

**Comment by coderaiser** [comment]
Any progress on this?

**Pull request closed without merging**
